version: '2.1'

volumes:
  files:
    driver: local
    driver_opts:
      type: nfs
      o: addr=<NFS_IP>,nolock,soft,rw
      device: :Path/To/NFS/owncloud # folder
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local
mht
services:

  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "9090:8080" # Traefik automatically chooses exposed port
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    labels:
      - traefik.docker.network=web
      - traefik.http.routers.owncloud-owncloud.rule=(Host("<Host Name>") && Path("/owncloud")) || Host("<owncloud.Host Name>")
      - traefik.http.routers.owncloud-owncloud.tls=true
      - traefik.http.routers.owncloud-owncloud.tls.certresolver=myresolver
    networks:
      - web
      - internal
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data

  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=password # Change this!
      - MARIADB_USERNAME=owncloud
      - MARIADB_PASSWORD=owncloud # Change this!
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup
    networks:
      - internal

  redis:
    image: webhippie/redis:latest
    restart: unless-stopped
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis
    networks:
      - internal

networks:
  web:
    external: true
  internal:
